### ISSUE TITLE
patternsが配列か文字列かで`i` flagの有無が変わってしまう

### ISSUE THREAD

**Issue by azu** [prh/prh#25]
patternに正規表現を、**文字列**として指定するか or **配列**として指定するかで挙動が変わってしまっているようです。

具体的には、配列の中に正規表現文字列を指定した場合 `i` フラグが無視されます。

Code:
```js
const engine = new Engine({
    version: 1,
    rules: [{
        expected: "vvakame",
        pattern: ["/vvakme/i"],
    }, {
        expected: "vvakame",
        pattern: "/vvakme/i",
    }],
});

console.log("pattern 0", engine.rules[0].pattern);
console.log("pattern 1", engine.rules[1].pattern);
```

Output:
```
pattern 0 /(?:vvakme)/gmu
pattern 1 /vvakme/gimu
```

よくありそうなユースケースでは、以下のようなケースが微妙な書き方の違いで結果が変わっているようです。

```yaml
anyversion: 1
rules:
  # これは /jquery/i として機能する
  - expected: jQuery
    pattern: /jquery/i
  # これは /jquery/i として機能しない
  - expected: jQuery
    pattern: 
      - /jquery/i
```

原因は[combine](https://github.com/prh/prh/blob/9bf76e171ad106dceb262630b77a3d2f81177ac5/lib/utils/regexp.ts#L37-L48 "combine")で`regexp.source`のみを結合するからのようです。
