### ISSUE TITLE
Question: patternとwordBoundaryオプションを同時に指定した場合の挙動

### ISSUE THREAD

**Issue by azu** [prh/prh#26]
patternと`wordBoundary`オプションを同時に指定した場合、
`\b`がそれぞれのパターンに追加されずに単に無視されてしまいます。

これは意図通りの動作でしょうか?

次の例は今の挙動だとspecが通りません。

>    Error: Angular$1 spec failed. "angulardart", expected "angulardart", but got "Angulardart", /(?:angular(js)?)/gimu

`\b`が追加されていないため、`angulardart`も変換されている。

```yml
  # patternsと共にwordBoundaryを指定した場合
  # それぞれのパターンの前後に \b が付与される
  - expected: Angular$1
    patterns:
      - /angular(js)?/i
    options:
      wordBoundary: true
    specs:
      - from: angular
        to: Angular
      - from: angularJS
        to: AngularJS
      - from: angulardart
        to: angulardart
```
