### ISSUE TITLE
patternsが配列 かつ キャプチャーを使う場合に $1 の参照先がずれる

### ISSUE THREAD

**Issue by azu** [prh/prh#32]
次のように複数のパターンでそれぞれがキャプチャーグループを指定したいた場合に、`$1`が空になったりします。

```yaml
version: 1

rules:
  - expected: ECMAScript $1
    patterns:
      - /ES (\d+)/i
      - /ES(\d+)/i
    specs:
      - from: ES 5
        to: ECMAScript 5
      - from: ES2015
        to: ECMAScript 2015 # これが "ECMAScript " になる
```

おそらく実装的にパターンの正規表現を結合しているため、仕様のようにも見えますがハマったので一応報告です。
`/(?:ES (\d+)|ES(\d+))/` というパターンに結合されるので、`/ES(\d+)/i`にマッチするケースでは`$1`が空文字になってしまう(`$2`に入っている)

名前付きキャプチャーで回避できるかなと思いましたが、名前付きキャプチャーは重複してはいけないみたいです。

>      SyntaxError: Invalid regular expression: /(?:ES (?<version>\d+)|ES(?<version>\d+))/: Duplicate capture group name

```yaml
version: 1

rules:
  - expected: ECMAScript $<version>
    patterns:
      - /ES (?<version>\d+)/i
      - /ES(?<version>\d+)/i
    specs:
      - from: ES 5
        to: ECMAScript 5
      - from: ES2015
        to: ECMAScript 2015
```

ワークアラウンドとしては、キャプチャを含むパターンを分離するぐらいですかね?

```yaml
version: 1

rules:
  - expected: ECMAScript $1
    patterns:
      - /ES (\d+)/i
    specs:
      - from: ES 5
        to: ECMAScript 5
  - expected: ECMAScript $1
    patterns:
      - /ES (\d+)/i
    specs:
      - from: ES2015
        to: ECMAScript 2015 # これが "ECMAScript " になる
```
